### ISSUE TITLE
Build for Windows

### ISSUE THREAD

**Issue by bergkvist** [conda-forge/graphblas-feedstock#8]
Can this be added to the pipeline?

**Comment by bergkvist** [comment]
Most, although not all GraphBLAS features are supported on Windows. 

See below for information on how to build GraphBLAS on Windows (taken from the [GraphBLAS UserGuide v3.3.3](http://mit.bme.hu/~szarnyas/grb/GraphBLAS_UserGuide.pdf), page 216-218)

![image](https://user-images.githubusercontent.com/410028/90132936-ef59c400-dd6e-11ea-8575-86b4a8c54ec4.png)
![image](https://user-images.githubusercontent.com/410028/90132995-039dc100-dd6f-11ea-9029-69c49ff13365.png)
![image](https://user-images.githubusercontent.com/410028/90133038-14e6cd80-dd6f-11ea-94de-15ee7b1c3033.png)

**Comment by basnijholt** [comment]
If you will make a PR that successfully builds on Windows, it will certainly be merged! :tada:
